// eslint-disable-next-line import/prefer-default-export
export const timetablePropertyMap = {
  Building: 'building',
  Description: 'description',
  Dist: 'distrib',
  Enrl: 'enrollment',
  FYS: 'fys',
  Instructor: 'instructor',
  Lim: 'limit',
  'Lrn Obj': 'learningObjective',
  'NR Eligible or CT/NC': 'creditOptions',
  Num: 'number',
  Period: 'period',
  'Period Code': 'periodCode',
  Room: 'room',
  Sec: 'section',
  Status: 'status',
  Subj: 'subject',
  Term: 'term',
  Text: 'text',
  Title: 'title',
  WC: 'wc',
  Xlist: 'xlist',
};
